#!/bin/bash
DIR=$(dirname "$(readlink -f "$0")")
cd ${DIR}/src
find */ -type d |
while read dirname
do
  cd ${DIR}/src/${dirname}
  echo "// This file will be overwritten.  It was generated by build.sh." > index.ts
  echo "" >> index.ts

  find . -mindepth 1 -maxdepth 1 -type d |
  while read curdir
  do
    curdirbase=$(basename ${curdir})
    echo "export * as ${curdirbase} from '${curdir}';" >> index.ts
  done

  ls *.ts |grep -v index.ts |
  while read curfile
  do
    curfilebase=$(basename ${curfile} .ts)
    echo "export * as ${curfilebase} from './${curfilebase}';" >> index.ts
  done
done
