version: '3.6'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  db:
    image: mariadb:10.5.5
    environment:
      MYSQL_USER: "mariadb"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: "UTC"
    ports:
      - "3306:3306"
  minio:
    image: minio/minio
    entrypoint: >
      /bin/sh -c "
      mkdir -p /data/yourbucket;
      /opt/bin/minio server /data;
      "
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_DIR=/data
    volumes:
      - ./test/datalake:/data
  ingress:
    build:
      context: .
      dockerfile: Dockerfile.test
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "./wait-for-it.sh -t 60 db:3306 && ./wait-for-it.sh -t 60 redis:6379 -- yarn test"
    environment:
      - DATALAKE_BUCKET=yourbucket
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PREFIX=cwes-test
      - REDIS_CLUSTER=false
      - DATABASE_NAME=exampledb
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=123456
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - minio
      - db
