FROM node:lts-alpine
WORKDIR /usr/src/app
# ENV DEBUG ioredis:*
RUN apk add --no-cache bash && chown -R node:node /usr/src/app
USER node:node
COPY --chown=node:node . /usr/src/app
RUN yarn install
RUN yarn build
CMD ["/bin/sh", "-c", "yarn test"]
