FROM node:lts-alpine

# ENV DEBUG ioredis:*
RUN apk add --no-cache bash 
USER node:node
COPY --chown=node:node . /usr/src/app
WORKDIR /usr/src/app
RUN yarn install \
 && yarn build \
 && yarn cache clean --all
 
CMD ["/bin/sh", "-c", "yarn test"]
